name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          echo "Triggering Render deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
